import type { Product } from "@/lib/types";

export const categories = ["Men", "Women", "Kids", "Shoes", "Accessories", "New Arrivals", "Sale"];
export const sizes = ["XS", "S", "M", "L", "XL", "XXL"];
export const colors = ["Black", "White", "Blue", "Green", "Red", "Tan"];

export const fallbackProducts: Product[] = [
  {
    id: "denim-jacket",
    name: "Denim Utility Jacket",
    description: "Structured denim jacket with roomy pockets, contrast stitching, and an easy everyday fit.",
    category: "Women",
    price: 2499,
    discountPrice: 1999,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Black"],
    stock: 20,
    images: ["https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=900&q=80"],
    featured: true,
    popular: true
  },
  {
    id: "linen-shirt",
    name: "Linen Camp Shirt",
    description: "Breathable linen blend shirt with a relaxed collar and soft garment-washed handfeel.",
    category: "Men",
    price: 1899,
    discountPrice: 1499,
    sizes: ["M", "L", "XL"],
    colors: ["White", "Tan", "Green"],
    stock: 14,
    images: ["https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80"],
    featured: true
  },
  {
    id: "kids-hoodie",
    name: "Kids Everyday Hoodie",
    description: "Soft fleece hoodie with ribbed cuffs, kangaroo pocket, and durable school-day stitching.",
    category: "Kids",
    price: 1299,
    discountPrice: 999,
    sizes: ["XS", "S", "M"],
    colors: ["Red", "Blue"],
    stock: 8,
    images: ["https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=900&q=80"],
    featured: false,
    popular: true
  },
  {
    id: "runner-sneaker",
    name: "Runner Knit Sneaker",
    description: "Lightweight knit sneaker with cushioned sole and clean styling for daily movement.",
    category: "Shoes",
    price: 3299,
    discountPrice: 2799,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White"],
    stock: 5,
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80"],
    featured: true
  },
  {
    id: "canvas-tote",
    name: "Canvas Market Tote",
    description: "Heavy canvas tote with reinforced handles and enough space for daily essentials.",
    category: "Accessories",
    price: 899,
    discountPrice: 699,
    sizes: ["M"],
    colors: ["Tan", "Black"],
    stock: 0,
    images: ["https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=80"],
    featured: false
  },
  {
    id: "sale-dress",
    name: "Pleated Midi Dress",
    description: "Fluid midi dress with subtle pleats, side pockets, and a polished weekend silhouette.",
    category: "Sale",
    price: 2999,
    discountPrice: 1899,
    sizes: ["S", "M", "L"],
    colors: ["Green", "Black"],
    stock: 3,
    images: ["https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=80"],
    featured: true,
    popular: true
  },
  {
    id: "oversized-tee",
    name: "Oversized Cotton Tee",
    description: "Heavyweight cotton tee with dropped shoulders, clean rib neck, and a relaxed streetwear shape.",
    category: "Men",
    price: 1199,
    discountPrice: 899,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Green"],
    stock: 28,
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80"],
    featured: true,
    popular: true
  },
  {
    id: "wide-leg-trousers",
    name: "Wide Leg Trousers",
    description: "Tailored high-rise trousers with fluid drape, side pockets, and a polished office-to-evening fit.",
    category: "Women",
    price: 2599,
    discountPrice: 2199,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Tan"],
    stock: 16,
    images: ["https://images.unsplash.com/photo-1551803091-e20673f15770?auto=format&fit=crop&w=900&q=80"],
    featured: true
  },
  {
    id: "kids-denim-overall",
    name: "Kids Denim Overall",
    description: "Durable denim overall with adjustable straps, easy pockets, and room for active play.",
    category: "Kids",
    price: 1699,
    discountPrice: 1299,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Blue"],
    stock: 11,
    images: ["https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=80"],
    featured: true
  },
  {
    id: "court-low-sneaker",
    name: "Court Low Sneaker",
    description: "Low-profile court sneaker with a padded collar, grippy sole, and crisp casual styling.",
    category: "Shoes",
    price: 2899,
    discountPrice: 2399,
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Green"],
    stock: 18,
    images: ["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=900&q=80"],
    featured: false,
    popular: true
  },
  {
    id: "leather-belt",
    name: "Classic Leather Belt",
    description: "Smooth leather belt with a brushed metal buckle and everyday styling for denim or tailoring.",
    category: "Accessories",
    price: 1099,
    discountPrice: 799,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Tan"],
    stock: 24,
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80"],
    featured: false
  },
  {
    id: "ribbed-knit-dress",
    name: "Ribbed Knit Dress",
    description: "Soft ribbed knit dress with a comfortable stretch fit and clean minimal finish.",
    category: "New Arrivals",
    price: 2799,
    discountPrice: 2299,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "Red", "Tan"],
    stock: 13,
    images: ["https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=900&q=80"],
    featured: true,
    popular: true
  },
  {
    id: "quilted-crossbody",
    name: "Quilted Crossbody Bag",
    description: "Compact quilted crossbody bag with an adjustable strap and secure zip compartments.",
    category: "Accessories",
    price: 1799,
    discountPrice: 1399,
    sizes: ["M"],
    colors: ["Black", "White", "Red"],
    stock: 9,
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=80"],
    featured: true
  },
  {
    id: "sale-chino",
    name: "Slim Stretch Chino",
    description: "Easy stretch chino with a clean slim fit and soft washed finish.",
    category: "Sale",
    price: 2199,
    discountPrice: 1299,
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Tan", "Green", "Black"],
    stock: 7,
    images: ["https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80"],
    featured: false,
    popular: true
  },
  {
    id: "kids-rain-jacket",
    name: "Kids Rain Jacket",
    description: "Lightweight hooded rain jacket with snap pockets and a water-resistant shell.",
    category: "Kids",
    price: 1899,
    discountPrice: 1499,
    sizes: ["XS", "S", "M", "L"],
    colors: ["Red", "Blue", "Green"],
    stock: 15,
    images: ["https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=900&q=80"],
    featured: false
  },
  {
    id: "platform-sandal",
    name: "Platform Strap Sandal",
    description: "Comfortable platform sandal with secure straps, cushioned footbed, and summer-ready height.",
    category: "Shoes",
    price: 2499,
    discountPrice: 1999,
    sizes: ["S", "M", "L"],
    colors: ["Tan", "Black", "White"],
    stock: 12,
    images: ["https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=80"],
    featured: true
  }
];

export const statusSteps = ["Order Placed", "Processing", "Shipped", "Out for Delivery", "Delivered"];
